### ISSUE TITLE
Replace clickable info dialogs with notifications

### ISSUE THREAD

**Issue by ghostbuster91** [elpassion/mainframer-intellij-plugin#72]
E.g. When we inject mainframer tasks we see dialog on which we need to click ok button. I dont think that such behaviour is needed. Green notification would be enough IMO

**Comment by ghostbuster91** [comment]
You should also replace it for `restore` action

**Comment by marcinsus** [comment]
I got error during injection :
`Cannot call invokeAndWait from the event dispatcher thread
java.lang.Error: Cannot call invokeAndWait from the event dispatcher thread
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1303)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
	at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348)
	at com.elpassion.intelijidea.util.UiKt.showBalloon(ui.kt:21)
	at com.elpassion.intelijidea.util.UiKt.showInfo(ui.kt:13)
	at com.elpassion.intelijidea.util.UiKt.showInfo$default(ui.kt:12)`

**Comment by pawegio** [comment]
@marcinsus threading issue fixed

**Comment by marcinsus** [comment]
👍

**Comment by pawegio** [comment]
@ghostbuster91 added
